name = "BitmapMapsExtras"
uuid = "91f7643b-a5d6-413a-971e-f956c21a1050"
version = "0.1.4"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DrawAndSpray = "80de0461-81d9-4176-ac57-184d3ad6c8ef"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqCore = "bbf590c4-e513-4bbe-9b18-05decba2e5d8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
